version: '3.8'

services:
  backend:
    build: .
    container_name: team_project_backend
    ports:
      - "9000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/project_db
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8080
      - WEAVIATE_GRPC_PORT=50051
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SERVER=${MAIL_SERVER}

      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    depends_on:
      - db
      - weaviate
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15-alpine
    container_name: team_project_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project_db
    ports:
      - "5432:5432"

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: team_project_weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      ENABLE_MODULES: 'text2vec-openai'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      AUTHENTICATION_ANONYMOUS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  postgres_data:
  weaviate_data: